flyer/urls.py
from django.conf.urls import patterns, url

from flyer import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

hermes/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hermes.views.home', name='home'),
    # url(r'^hermes/', include('hermes.foo.urls')),
	url(r'^flyer/', include('flyer.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

flyer/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
# store: store,url,flyer_crawl,country,province,city,postalcode,insert,update
class Store(models.Model):
    store = models.CharField(max_length=50)
    url = models.CharField(max_length=200, blank=True)
    flyer_crawl = models.TextField(blank=True)
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.store


#location: store,flyer_crawl,country,province,city,postal_code,insert,update
#self.store + ' ' + self.country + ' ' + self.city + ' ' + self.street + ' ' + self.postalcode
class Location(models.Model):
    store = models.ForeignKey(Store)
    flyer_crawl = models.TextField(blank=True)
    country = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    postalcode = models.CharField(max_length=50)
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return unicode(self.store) + ' : ' + self.country + ' : ' + self.province + ' : ' + self.city + ' : ' + self.street + ' : ' + self.postalcode

#flyer: flyer,location,start_date,end_date,insert,update
class Flyer(models.Model):
    flyer = models.CharField(max_length=100)
    location = models.ForeignKey(Location)
    start_date = models.DateTimeField('start date')
    end_date = models.DateTimeField('end date')
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.flyer
    def current_flyer(self):
        return self.start_date <= timezone.now() <= self.end_date
    current_flyer.admin_order_field = 'start_date'
    current_flyer.boolean = True
    current_flyer.short_description = 'Current Flyer?'

#product: product,insert,update
class Product(models.Model):
    product = models.CharField(max_length=50)
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.product

#brand: brand,insert,update
class Brand(models.Model):
    brand = models.CharField(max_length=50)
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.brand

#category: category,insert,update
class Category(models.Model):
    category = models.CharField(max_length=50)
    insert = models.DateTimeField('inserted date', auto_now_add=True)
    update = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.category

#sale: product,brand,category,flyer,price_sale,price_reg,unit,description,insert,update
class Sale(models.Model):
    product = models.ForeignKey(Product)
    brand = models.ForeignKey(Brand)
    category = models.ForeignKey(Category)
    flyer = models.ForeignKey(Flyer)
    price_sale = models.IntegerField(default=0)
    price_reg = models.IntegerField(default=0, blank=True)
    unit = models.CharField(max_length=10, blank=True)
    description = models.TextField()
    insert_date = models.DateTimeField('inserted date', auto_now_add=True)
    update_date = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return unicode(self.product)

#saving: sale,saving,value,insert,update
class Saving(models.Model):
    sale = models.ForeignKey(Sale)
    value = models.IntegerField(default=0)
    saving = models.CharField(max_length=100)
    insert_date = models.DateTimeField('inserted date', auto_now_add=True)
    update_date = models.DateTimeField('updated date', auto_now=True)
    def __unicode__(self):
        return self.saving

flyer/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader

from flyer.models import Sale
from flyer.models import Saving

def index(request):

    all_sales = Sale.objects.order_by('-price_sale')
    template = loader.get_template('flyer/index.html')

    context = RequestContext(request, {
        'all_sales': all_sales,
    })

    return HttpResponse(template.render(context))

flyer/templates/flyer/base.html
{% load static %}

<html>
<head>
<title>This is in the base</title>
<link rel="stylesheet" type="text/css" href="/static/flyer/bootstrap/css/bootstrap-theme.css">
<link rel="stylesheet" type="text/css" href="/static/flyer/style.css">
</head>
<body>
	{%block content%}

	{%endblock%}
</body>

</html>

flyer/templates/flyer/index.html
{% extends "flyer/base.html" %}


{%block content%}
{% if all_sales %}
    <table>
    {% for sale in all_sales %}
        <tr>
        	<td>{{ sale.product }}</td>
        	<td>{{ sale.brand }}</td>
        	<td>{{ sale.category }}</td>
        	<td>{{ sale.flyer }}</td>
        	<td>{{ sale.price_sale }}</td>
        	<td>{{ sale.price_reg }}</td>
        	<td>{{ sale.unit }}</td>
        	<td>{{ sale.description }}</td>
        	<td>
        			<ul>
					{% for saving in sale.saving_set.all %}
					    <li>{{ saving.saving }}</li>
					{% endfor %}
					</ul>
        	</td>	
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No sales are available.</p>
{% endif %}
{%endblock%}

flyer/templates/index.html
{% if all_sales %}
    <table>
    {% for sale in all_sales %}
        <tr>
        	<td>{{ sale.product }}</td>
        	<td>{{ sale.brand }}</td>
        	<td>{{ sale.category }}</td>
        	<td>{{ sale.flyer }}</td>
        	<td>{{ sale.price_sale }}</td>
        	<td>{{ sale.price_reg }}</td>
        	<td>{{ sale.unit }}</td>
        	<td>{{ sale.description }}</td>
        	<td>{{ sale.insert }}</td>
        	<td>{{ sale.update }}</td>
        	
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No sales are available.</p>
{% endif %}